name = "AshbornRP Modpack Client"
author = "AshbornRP Team"
version = "0.0.7-exp"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "de6fc5397d239a24e634fef9e21067cc7d44edb389ce7d3eaeb242828657b52d"

[versions]
fabric = "0.17.2"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20.1"]
