name = "AshbornRP Modpack Client"
author = "AshbornRP Team"
version = "0.0.17-exp"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "43b05bfd1380497534dc85f38f28751fe479418c2f9fd83f858d5ae08e07f550"

[versions]
fabric = "0.17.2"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20.1"]
