name = "AshbornRP Modpack Client"
author = "AshbornRP Team"
version = "0.0.11"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "090ac53306e63ce46e3067eaad8cfb69c2b7d95ba883ca4114f997019486b01e"

[versions]
fabric = "0.17.2"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20.1"]
