name = "AshbornRP Modpack Client"
author = "AshbornRP Team"
version = "0.0.9-exp"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4eea0f2cdef46bf3210cee6f856a87fa36cb9555b37c1960a18c1ffb9087ffd7"

[versions]
fabric = "0.17.2"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20.1"]
