name = "AshbornRP Modpack Client"
author = "AshbornRP Team"
version = "0.0.4-exp"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7ed90e7d0df724c4001b800897c6c2c28132d1444db63e868146567b9e9be9ce"

[versions]
fabric = "0.17.2"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20.1"]
