name = "AshbornRP Modpack Client"
author = "AshbornRP Team"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a74425bc65eac7e09d2c5f3346845af4b78450007b10c3cefa9137ae54869f69"

[versions]
fabric = "0.17.2"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20.1"]
