name = "AshbornRP Modpack Client"
author = "AshbornRP Team"
version = "0.0.5-exp"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "42adde4ef0fbf3b346ea51c530cbaadcec1a48acaa8fe8a42f080486437d5661"

[versions]
fabric = "0.17.2"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20.1"]
