# unsup configuration for automatic updates
[update]
# URL where pack index is hosted
url = "https://ashbornrp.github.io/public/releases/pack-client/index.toml"

# Optional: Update channel (stable, beta, alpha)
channel = "stable"

# Optional: Check interval in minutes (default: 60)
check_interval = 60

# Optional: Show update notifications
show_notifications = true